### ISSUE TITLE
Fix the jankiness in the list section

### ISSUE THREAD

**Issue by sarajw** [jeffreycharters/station#34]
Suspect it's something to do with it being centred. Have a go at fixing it up so it's not so wonky!

**Comment by RohitRajvaidya5** [comment]
Is this issue resolved I want to contribute

**Comment by sarajw** [comment]
Feel free! Go ahead :)

**Comment by RohitRajvaidya5** [comment]
Done!

**Comment by RohitRajvaidya5** [comment]
I just want to ask can add issue tag "hacktoberfest" so it can count on? This is my first time of hacktoberfest.

**Comment by RohitRajvaidya5** [comment]
You can merge now.

**Comment by publikphigor** [comment]
I just pulled upstream and resolved merge conflicts. This issue is still not resolved yet.
I will now go ahead and fix it.
